name: Deploy imagem do Job no Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar SDK do GCP
        run: gcloud config set project t-sunlight-454318-h7

      - name: Configurar Docker para autenticar no Artifact Registry
        run: |
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev

      - name: Build da imagem Docker
        run: docker build -t southamerica-east1-docker.pkg.dev/t-sunlight-454318-h7/etl-jobs/run-case-boticario-paulolima .

      - name: Push da imagem para Artifact Registry
        run: docker push southamerica-east1-docker.pkg.dev/t-sunlight-454318-h7/etl-jobs/run-case-boticario-paulolima