name: Deploy no Cloud Run

on:
  push:
    branches:
      - main  # Deploy automático ao fazer push na branch main
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar Google Cloud SDK
        run: gcloud config set project t-sunlight-454318-h7

      - name: Construir e enviar a imagem Docker
        run: |
          export CLOUDSDK_CORE_LOGGING_ONLY=true
          gcloud builds submit \
            --tag gcr.io/t-sunlight-454318-h7/run-case-boticario-paulolima \
            --gcs-log-dir=gs://logs-boticario-paulolima/logs/

      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy run-case-boticario-paulolima \
            --image gcr.io/t-sunlight-454318-h7/run-case-boticario-paulolima \
            --platform managed \
            --region southamerica-east1 \
            --allow-unauthenticated